### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/waffle-server-import-cli#2]
I can login to a server on windows but:

1. when registering a repository, apparently it doesn't work (`.ws-importer-cli/repositories` folder stays empty)
2. the following error is shown for commands update/rollback/check state (and maybe more, I didn't dare to touch)

![image](https://cloud.githubusercontent.com/assets/1596071/19198288/ab1106aa-8cbe-11e6-8d4f-5f895986a494.png)

I suppose it's a windows thing...

**Comment by rychkog** [comment]
Only `git@github.com:VS-work/ddf--gapminder--systema_globalis.git` notion is supported
You shoud use only `SSH` urls

**Comment by jheeffer** [comment]
Okay, I'll try that
