### ISSUE TITLE
Reword "results overview" to “list datasets and versions"

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/waffle-server-import-cli#3]
i think “results overview” is a bit unclear: if it’s the results of the latest transaction or an overview of what an endpoint has or both

i’d suggest wording it differently: “list datasets and versions"

also please place it as the first item in the menu (let every workflow to start from knowing what we have)

**Comment by vvpanchenko** [comment]
@AlexTsap have fixed this issue
